immutable:
  username: "shine"
  password: "!q@w#e$r"

record:
  username: "novel"
  password: "1q2w3e4r"

player:
  name: "sirus"
  phone: "1234567890"
  address:
    city: "Eye of the Storm"
    zip: "36472"
